- .github/workflows/c-cpp.yml
- include/gui/helper.h
- include/gui/input_dialog.h
- include/gui/main_window.h
- include/gui/popup_selection.h
- include/solver/constraint.h
- include/solver/dfpn.h
- include/solver/game.h
- include/solver/helper.h
- include/solver/node.h
- linux_build.sh
- src/gui/board_cell.cpp
- src/gui/helper.cpp
- src/gui/input_dialog.cpp
- src/gui/main_window.cpp
- src/gui/popup_selection.cpp
- src/main.cpp
- src/solver/constraint.cpp
- src/solver/dfpn.cpp
- src/solver/fillgame.cpp
- src/solver/game.cpp
- src/solver/node.cpp
- test/solver_test.cpp
> DEV: add winning conditions, info, UI update; FIX: multiple instances of cells

- .github/workflows/c-cpp.yml
- .gitmodules
- CMakeLists.txt
- README.md
- include/solver/constraint.h
- src/CMakeLists.txt
- src/solver/constraint.cpp
- src/solver_main.cpp
- test/CMakeLists.txt
- test/solver_test.cpp
~~Windows CI may cause a lot of trouble because of Qt.~~
Windows CI does cause a lot of trouble, but because of compiling errors.
> feat: add Windows CI

- .github/workflows/c-cpp.yml
- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- include/solver/dfpn.h
- include/solver/minimax.h
- include/solver/node.h
- linux_build.sh
- src/solver/minimax.cpp
- src/solver/node.cpp
- src/solver_main.cpp
- test/README.md
- test/dfpn_test.h
- test/minimax_test.h
- test/test_main.cpp
> DEV: minimax algo

- include/solver/helper.h
- include/solver/minimax.h
- linux_build.sh
- src/solver/minimax.cpp
- test/alphabeta_test.h
- test/minimax_test.h
- test/test_main.cpp
> DEV: minimax with alphabeta

- include/solver/minimax.h
- include/solver/negamax.h
- include/solver/node.h
- src/solver/minimax.cpp
- src/solver/negamax.cpp
- src/solver/node.cpp
- src/solver_main.cpp
- test/alphabeta_test.h
- test/dfpn_test.h
- test/minimax_alphabeta_test.h
- test/minimax_test.h
- test/negamax_alphabeta_test.h
- test/negamax_test.h
- test/test_main.cpp
> DEV: Negamax and its alpha-beta prunning version

- include/solver/dfpn.h
- include/solver/negamax.h
- include/solver/node.h
- src/solver/dfpn.cpp
- src/solver/negamax.cpp
- src/solver/node.cpp
- src/solver_main.cpp
- test/negamax_alphabeta_tt_test.h
- test/test_main.cpp
> DEV: negamax with alphabeta and transposition table

- include/solver/negamax.h
- include/solver/node.h
- src/solver/negamax.cpp
- src/solver/node.cpp
close #32 
@Samarium150 do you know an easier way to use template for a class member variable?
I was thinking
```
class NodeType { // has NodeType::Node, and NodeType::NodeTT };
class Node {
template<NodeType??> T
std::vector<T> children_;
}
class NodeTT : public Node {}
```
anyway, this is not very urgent
> separate node and nodett

- include/solver/minimax.h
- include/solver/negamax.h
- include/solver/node.h
- src/solver/minimax.cpp
- src/solver/negamax.cpp
- src/solver/node.cpp
- src/solver_main.cpp
- test/minimax_alphabeta_tt_test.h
- test/test_main.cpp
> DEV: implement minimax alphabeta transposition table

- src/solver/game.cpp
- Fixed an issue with the Pos.is_important variable being generated and used in Game.cpp
- This speeds up all test cases runtime from ~17,000ms to ~9600ms.
> Issue #25 -- Move Ordering

- README.md
- include/solver/constraint.h
- src/solver/constraint.cpp
- src/solver_main.cpp
> feat: implement constraint on Windows (probably)

- include/gui/board_cell.h
- include/solver/constraint.h
- include/solver/dfpn.h
- include/solver/game.h
- include/solver/helper.h
- include/solver/minimax.h
- include/solver/negamax.h
- include/solver/node.h
- include/solver/pns.h
- include/solver/pns_node.h
- src/gui/main_window.cpp
- src/solver/minimax.cpp
- src/solver/negamax.cpp
- src/solver/node.cpp
- src/solver/pns.cpp
- src/solver/pns_node.cpp
- src/solver_main.cpp
> DEV: optimize class member scope

- .vscode/c_cpp_properties.json
- .vscode/settings.json
also see #47 issue description
> BUG: fix vscode+qt

- .gitignore
- CMakeLists.txt
- README.md
- include/solver/helper.h
- run_experiments.sh
- src/solver/helper.cpp
- test/CMakeLists.txt
- test/experiments.cpp
- test/plot.py
- test/plots.py
> feat: implement peak memory usage measure

- .vscode/launch.json
- CMakeLists.txt
- fillgame.qrc
- include/gui/board_cell.h
- include/gui/info_dock.h
- include/gui/main_window.h
- include/gui/popup_selection.h
- resource/custom_qss/info_dock.qss
- src/gui/board_cell.cpp
- src/gui/info_dock.cpp
- src/gui/main_window.cpp
- src/gui/popup_selection.cpp
- src/gui_main.cpp
> DEV: improve UI

- .vscode/settings.json
- include/gui/board_cell.h
- include/gui/helper.h
- include/gui/info_dock.h
- include/gui/input_dialog.h
- include/gui/main_window.h
- include/gui/main_window_menu_bar.h
- include/gui/worker.h
- src/gui/board_cell.cpp
- src/gui/helper.cpp
- src/gui/info_dock.cpp
- src/gui/input_dialog.cpp
- src/gui/main_window.cpp
- src/gui/main_window_menu_bar.cpp
- src/gui/worker.cpp
> DEV: solver frozen GUI

- .vscode/c_cpp_properties.json
- .vscode/settings.json
- CMakeLists.txt
- include/gui/helper.h
- include/gui/info_dock.h
- include/gui/ip_settings.h
- include/gui/main_window.h
- include/gui/main_window_menu_bar.h
- include/gui/new_game_window.h
- include/gui/settings.h
- include/gui/tcp_client.h
- include/gui/tcp_server.h
- src/CMakeLists.txt
- src/gui/helper.cpp
- src/gui/info_dock.cpp
- src/gui/input_dialog.cpp
- src/gui/ip_settings.cpp
- src/gui/main_window.cpp
- src/gui/main_window_menu_bar.cpp
- src/gui/new_game_window.cpp
- src/gui/settings.cpp
- src/gui/tcp_client.cpp
- src/gui/tcp_server.cpp
- src/gui/worker.cpp
> DEV: communicataion between applications

- src/gui/info_dock.cpp
- src/gui/main_window.cpp
- src/gui/main_window_menu_bar.cpp
- src/gui/new_game_window.cpp
> tr() QString

- include/solver/helper.h
- test/CMakeLists.txt
- test/experiments.cpp
- test/other_tests/twoD_vs_oneD.cpp
> feat: 2d vs 1d tests

- include/solver/game.h
- src/gui/main_window.cpp
- src/solver/game.cpp
- src/solver/node.cpp
- src/solver/pns.cpp
- src/solver_main.cpp
- simplify if-condition in `getPossibleMove` !(!A and B) -> !(!A) or !B -> A or !B -> A (the last transition is because `is_expanded_` has the same effect as `possible_moves_.empty()`
- combine `getEmptyPositions` and `getFilledPositions`
- early return for flood fill (for size > value case)
- remove valid game string checking upon game creation
- only check at the very first 
- major data structure change: `std::unordered_map<Pos, std::vector<uint8_t>>` to `std::vector<Pos, uint8_t>` for sorting 695f96d6e8a07770e22600eea3ec89278d54633c. we examine the smallest value first
close #25
> DEV: optimizations on Game class

- include/solver/dfpn.h
- src/solver/dfpn.cpp
- src/solver/game.cpp
- src/solver_main.cpp
- test/algorithm_test_cases.h
- test/dfpn_test.h
- test/game_string_test.h
- test/minimax_alphabeta_test.h
- test/minimax_alphabeta_tt_test.h
- test/minimax_test.h
- test/negamax_alphabeta_test.h
- test/negamax_alphabeta_tt_test.h
- test/negamax_test.h
- test/other_tests/README.md
- test/other_tests/twoD_vs_oneD.cpp
- test/pns_test.h
- test/test_main.cpp
> DEV: central test cases

- test/algorithm_test_cases.h
- test/minimax_alphabeta_test.h
- test/minimax_alphabeta_tt_test.h
- test/minimax_test.h
- test/negamax_alphabeta_test.h
- test/negamax_alphabeta_tt_test.h
- test/negamax_test.h
- test/pns_test.h
Closes #65 
Let's see if CI passes
> fix: gtest

- .gitignore
- include/solver/helper.h
- include/solver/minimax.h
- include/solver/negamax.h
- include/solver/node.h
- include/solver/pns.h
- include/solver/pns_node.h
- linux_build.sh
- src/solver/minimax.cpp
- src/solver/negamax.cpp
- src/solver/pns.cpp
- src/solver_main.cpp
- test/algorithm_test_cases.h
- test/other_tests/README.md
- test/other_tests/agent_fight.cpp
- test/other_tests/twoD_vs_oneD.cpp
> Agent Playing against each other

- include/solver/mcts.h
- src/solver/mcts.cpp
- test/algorithms/mcts_test.h
> Fixed MCTS best move selection (#74)

- include/solver/mcts.h
- include/solver/minimax.h
- include/solver/negamax.h
- include/solver/pns.h
- src/solver/helper.cpp
- src/solver/mcts.cpp
- src/solver/minimax.cpp
- src/solver/negamax.cpp
- src/solver/pns.cpp
- src/solver_main.cpp
- Implemented node counts for every algorithm except DFPN
- Included node counts as a metric reported by experiments.cpp
- Fixed the node count for DFPN
- it was previously counting them incorrectly (and was far lower than what it actually is)
> Implement node counts for every algorithm and experiments
